### PR TITLE
Image uploader candidate

### PR DESCRIPTION
**Pull request by ACSG-64**
I developed an image uploader from scratch using [busboy](https://www.npmjs.com/package/busboy) and for image processing any package that allows to process file streams (like for example [sharp](https://www.npmjs.com/package/sharp)) could be used. The uploader is optimized to process incoming images using streams without allocating temporary buffers. It also parses the form body fields.
Please read comments below.

### CODE REVIEW

**Comment by ACSG-64** [comment]
I don't know how to test this uploader, so I made a mini server for manual testing of this uploader. I would appreciate if you (_anyone who is reading this._) could take a look at it and provide feedback: 

- Implementation demo: https://replit.com/@ACSG/Custom-image-uploader-demo#server.js
- Running demo: https://custom-image-uploader-demo.acsg.repl.co/

**Comment by ACSG-64** [comment]
To those of you who have kindly asked to review the uploader code, you will probably find it confusing, so if you need clarifications please let me know. As I don't think this is a final version of the uploader, I would welcome suggestions. 
_Again, you can see the implementation of this component in the links of the previous comment. Thanks!_

**Comment by shno784** [comment]
I don't understand the implementation at all, works like how you expect it to though.

**Comment by ACSG-64** [comment]
I'm going to postpone this again. Read my comment I posted on the issue #36

**Pull request closed without merging**
